/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gdm;

import gdm.entidades.clases.Anticipo;
import gdm.entidades.clases.ContratoCliente;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.Clases.ContratoClienteNegocio;

/**
 *
 * @author Chuy
 */
public class JDialogContratoCliente extends javax.swing.JDialog {

    /**
     * Creates new form JDialogContratoCliente
     */
    public JDialogContratoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public int idContrato = 0;
    private List<ContratoCliente> contratos;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Abonar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setMaximumSize(new java.awt.Dimension(1134, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1134, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1134, 650));

        tblContratos.getTableHeader().setFont(new java.awt.Font("Euphemia", 0, 18));
        tblContratos.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Folio", "Nombre completo", "Modelo", "Triptico", "Reconocimiento", "Agradecimiento", "Dirigido a:", "Foto panorámica", "Foto estudio", "Foto misa", "Material de anillos", "kilates", "Gramos", "Renta de toga", "Misa", "Baile", "Mesa extra", "Fotos extra", "Triptico", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContratos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblContratos.setRowHeight(23);
        tblContratos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblContratos);
        if (tblContratos.getColumnModel().getColumnCount() > 0) {
            tblContratos.getColumnModel().getColumn(0).setMinWidth(0);
            tblContratos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblContratos.getColumnModel().getColumn(0).setMaxWidth(0);
            tblContratos.getColumnModel().getColumn(1).setMinWidth(80);
            tblContratos.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblContratos.getColumnModel().getColumn(1).setMaxWidth(80);
            tblContratos.getColumnModel().getColumn(2).setMinWidth(250);
            tblContratos.getColumnModel().getColumn(2).setPreferredWidth(250);
            tblContratos.getColumnModel().getColumn(2).setMaxWidth(250);
            tblContratos.getColumnModel().getColumn(3).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(3).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(5).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(5).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(6).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(6).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(7).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(7).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(8).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(8).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(9).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(9).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(9).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(10).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(10).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(10).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(11).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(11).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(11).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(12).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(12).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(12).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(13).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(13).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(13).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(14).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(14).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(14).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(15).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(15).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(15).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(17).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(17).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(17).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(18).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(18).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(18).setMaxWidth(100);
            tblContratos.getColumnModel().getColumn(19).setMinWidth(50);
            tblContratos.getColumnModel().getColumn(19).setPreferredWidth(50);
            tblContratos.getColumnModel().getColumn(19).setMaxWidth(50);
            tblContratos.getColumnModel().getColumn(20).setMinWidth(100);
            tblContratos.getColumnModel().getColumn(20).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(20).setMaxWidth(100);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Editar1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Abonar.setText("Abonar");
        Abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbonarActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Eliminar1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Agregar1.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar2.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gdm/entidades/imagenes/Aceptar3.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(93, 93, 93)
                        .addComponent(Abonar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(265, 265, 265)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Abonar)
                        .addGap(13, 13, 13)))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: 
        JDialogAgregarContratoCliente cc = new JDialogAgregarContratoCliente(null, rootPaneCheckingEnabled);
        cc.idContrato = idContrato;
        cc.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbonarActionPerformed
        // TODO add your handling code here:
        try
        {
         this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(tblContratos.getSelectedRow()!= -1)
            {    
                JDialogAgregarAnticipo frame = new JDialogAgregarAnticipo(null, true);
                //frame.idContratoCliente =  Integer.parseInt(tblContratos.getValueAt(tblContratos.getSelectedRow(), 0).toString());
                //frame.total =  Double.parseDouble(tblContratos.getValueAt(tblContratos.getSelectedRow(), 17).toString());
                frame.idContratoCliente = 2;
                frame.total = 3500;
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }  
        }
        catch(Exception ex)
        {
            
        }finally
        {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_AbonarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          cargarContratos();

    }//GEN-LAST:event_formWindowOpened

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abonar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContratos;
    // End of variables declaration//GEN-END:variables

    private void cargarContratos() {
      
       DefaultTableModel mod = (DefaultTableModel)tblContratos.getModel();
        while(mod.getRowCount() > 0)
            mod.removeRow(0);
        
        contratos = ContratoClienteNegocio.Listado();
        for(ContratoCliente contrato : contratos){
            int id = contrato.getId();
            String nombre= contrato.getCliente().getNombre();
            int folio = contrato.getFolio();
            boolean triptico= contrato.isTriptico();
            String modelo= contrato.getModelo().getNombre();
            boolean reconocimiento= contrato.isReconocimiento();
            String agradecimiento= contrato.getAgradecimiento().getClave();
            boolean fotoPanoramica= contrato.getFotoPanoramica();
            boolean fotoEstudio= contrato.isFotoEstudio();
            boolean fotoMisa= contrato.isFotoMisa();
            String anillo= contrato.getAnillo().getMetal().getNombre();
            double k= contrato.getAnillo().getK();
            double g= contrato.getAnillo().getG();
            boolean rentaToga = contrato.isRentaToga();
            boolean misa= contrato.isMisa();
            boolean baile = contrato.isBaile();
            int mesaExtra = contrato.getMesaExtra();
            int fotosExtra= contrato.getFotosExtra();
            double precio = contrato.getPrecio();
            Date fechaEntregaPaquete = contrato.getFechaEntregaPaquete();
            Date fechaEntregaDatos= contrato.getFechaEntregaDatos();
            Date fechaLimitePago=contrato.getFechaLimitePago();
            Date fechaContrato= contrato.getFechaContrato();
            String Comentarios = contrato.getComentarios();
            
            
           
                                           
            mod.addRow(new Object[] {id,folio,nombre, modelo ,triptico,reconocimiento ,agradecimiento ,fotoPanoramica,fotoEstudio,
            fotoMisa,anillo,k,g,rentaToga,misa,baile,mesaExtra,fotosExtra,fechaContrato,precio,Comentarios,
            fechaEntregaPaquete,fechaEntregaDatos,fechaLimitePago});
        }
        
        tblContratos.setModel(mod);
    }   
    

}
